### ISSUE TITLE
How to rename the channels of switch?

### ISSUE THREAD

**Issue by fabiohblage** [Alperen-Ozturk/homebridge-tuya-switch#1]
Hello, thank you very much for your contribution,

I have a 4 channel switch, is it possible to rename each channel individually?

**Comment by OzturkAlperen** [comment]
Hey there,

Yes you can rename each channel individually regardless of the number of channels.

You need to do it in the Home app, not in the plugin configuration. Go into Home app, long press the switch that you wish to rename it’s channels. After that there must be a settings icon at the bottom left of the screen, press that and there will be some options to configure the switch. Click the “Accessories” option and in there you will see each channel as a seperate tile. Long press the channel you wish to rename, click the settings icon at the bottom left again and in there you can rename it.

I hope this helps.

**Comment by fabiohblage** [comment]
Yes, through the homekit app I had managed,

I figured there was a way to rename the plugin.
