### ISSUE TITLE
homebridge-tuya-switch and homebridge-tuya

### ISSUE THREAD

**Issue by Cerg1102** [Alperen-Ozturk/homebridge-tuya-switch#3]
I have several smart plugs and smart swiches and try to install homebridge-tuya-switch together with homebridge-tuya,  to get wortking all, but is not possible,  I get this error in homebridge log:

[4/17/2021, 8:00:28 PM] The requested platform 'TuyaLan' has been registered multiple times. Please be more specific by writing one of: homebridge-tuya.TuyaLan, homebridge-tuya-switch.TuyaLan

Any solution, 

Regards,

**Comment by OzturkAlperen** [comment]
Sorry, you can’t use these two plugins at the same time.

However as far as i know @iRayanKhan has implemented the functionality of this plugin to his plugin. At least i know that he merged my pull request. Try to use his plugin for switches the same way you use this plugin. If it doesn’t work. Go ahead and open an issue there.

Hope this helps.

**Comment by iRayanKhan** [comment]
Thought I added it in, I must have merged into the wrong branch. 

I'll have it added Friday. Thanks!

**Comment by iRayanKhan** [comment]
I see it in the plugin, under [lib/switchAccessory.js](https://github.com/iRayanKhan/homebridge-tuya/blob/main/lib/SwitchAccessory.js), is it not working for you?

Make sure you're on 2.0.1

**Comment by Cerg1102** [comment]
> I see it in the plugin, under [lib/switchAccessory.js](https://github.com/iRayanKhan/homebridge-tuya/blob/main/lib/SwitchAccessory.js), is it not working for you?
> 
> Make sure you're on 2.0.1

Not is not working!

<img width="700" alt="Captura de pantalla 2021-04-22 a las 20 20 59" src="https://user-images.githubusercontent.com/63961798/115766649-7f451880-a3a8-11eb-9409-9c250787a760.png">

Yes I have 2.0.1 version

<img width="835" alt="Captura de pantalla 2021-04-22 a las 20 23 39" src="https://user-images.githubusercontent.com/63961798/115766804-ad2a5d00-a3a8-11eb-9b9d-441b81d47136.png">

**Comment by Cerg1102** [comment]
any news about!

**Comment by iRayanKhan** [comment]
It exists in the plugin, I just have to update the schema. Please wait for the next update :)

**Comment by Cerg1102** [comment]
Perfect! Thanks a lot! :-)
