### ISSUE TITLE
Getting the config info

### ISSUE THREAD

**Issue by boboxx** [Alperen-Ozturk/homebridge-tuya-switch#4]
Were can I find the ID and Key for my switches?

**Comment by boboxx** [comment]
I was able to retrieve my keys

**Comment by miguelchico** [comment]
@boboxx how did you manage to get id and key?

**Comment by boboxx** [comment]
I ended up using a android emulator on a VM, loaded the Tuya Smart app and then copied ou the db once it had sync

**Comment by miguelchico** [comment]
Oh my...... thank you for the super quick response... I'll keep investigating

**Comment by boboxx** [comment]
I',m not in the process of moving all my Tuya device to Tazmota to that I can get off the cloud. I tried a few of the Tuya plugin but they all had issue and it wasn't relay reliable.
