### ISSUE TITLE
TuyaLan registered multiple times

### ISSUE THREAD

**Issue by beze** [Alperen-Ozturk/homebridge-tuya-switch#6]
Hello, 

First of all congrats on the plugin. 

I would like to use both, your tuya-switch, and the regular tuya-lan together, since I have multiple Tuya devices. 

But happens that when I install and setup both, this error appears on Homebridge startup:

`The requested platform 'TuyaLan' has been registered multiple times. Please be more specific by writing one of: homebridge-tuya.TuyaLan, homebridge-tuya-switch.TuyaLan`

Any idea about how to solve it?

**Comment by OzturkAlperen** [comment]
I did stop supporting this plugin a while ago because this plugin was meant to be just a temporary solution.

As I made a pull request years ago, abilities of this plugin is already added to this one:

https://github.com/iRayanKhan/homebridge-tuya

Instead of using the plugin you mentioned, you can use this one because this one is also based on the one you mentioned with new additions.

If you have another issue, feel free to ask again.


P.S. This situation was already stated in the Readme.

**Comment by beze** [comment]
Thanks for the clarifications! Cheers

**Comment by pandizajner** [comment]
@Alperen-Ozturk I've switched to `homebridge-tuya` already, but still facing a similar issue.
Do you have an idea what accessory type I should select to expose the device as a "Switch" type (with multi-outlet – it's a 2gang light switch). I tried SimpleLight using `"outletCount":2` but doesn't work. `MultiOutlet" doesn't have "switch" as an option though (only Power Point, Fan and Light).

<img width="728" alt="image" src="https://user-images.githubusercontent.com/1434834/210560577-26d635a1-8692-4a6f-95ef-609b3428fa80.png">

**Comment by OzturkAlperen** [comment]
Don't use the GUI configurator, directly edit the config.json file as stated in [here](https://github.com/Alperen-Ozturk/homebridge-tuya-switch/blob/master/config-example.MD).

I hope this answers your question.

**Comment by beze** [comment]
Just FYI, your plugin works perfect, it identifies and makes switches work perfectly. 

Same configuration using the merged  homebridge-tuya, does not work, all switches return the following error: 

`[TuyaDiscovery] Failed to parse discovery raw message on port 6667` Only for the Switch type devices. 

I'll try to figure it out, cheers m8.

**Comment by OzturkAlperen** [comment]
I did stop supporting this plugin after the maintainer of homebridge-tuya merged my pull request. Any other commit made after that date may have broken things. Sorry but I am not able to help you any further right now.

P.S. Maybe in the later future I might overhaul this plugin to support all Tuya accessories available. But that won't happen anytime soon sadly.

**Comment by pandizajner** [comment]
@Alperen-Ozturk Thank you, it helped. I used the exact same configuration for the switch in `homebride-tuya` as I was using for `homebridge-tuya-switch` and it works. The GUI was misleading me.

-- 

Leaving for anybody facing the same issue I had:
if you switched already from this plugin to `homebridge-tuya`, this is an example of working config:
```
{
                    "type": "Switch",
                    "name": "mySwitch",
                    "id": "<your_device_id_here>",
                    "key": "<your_device_key_here>",
                    "manufacturer": "MOES",
                    "model": "WIFI+RF Smart Switch (ZSQB-SM-21WR-EU-W)",
                    "switchCount": 2
                } 
```
