### ISSUE TITLE
Video Link is Broken

### ISSUE THREAD

**Issue by siniradam** [Alperen-Ozturk/homebridge-tuya-switch#7]
To get ID and Key Watch [this](https://www.youtube.com/watch?v=oq0JL_wicKg) video.
This URL redirects to a private video. Is there an up to date version?

**Comment by OzturkAlperen** [comment]
You can use [this](https://github.com/TuyaAPI/cli) tool. I think you can find plenty of tutorials that explains installation and usage of this tool.
